const dbquestions = [
  'Share what you did this summer.',
  'Maya is a 5th grader with ADHD. She has difficulty controlling her fidgeting and hyperactivity while in class. What solutions might you design to help with this problem?',
  'Where do you see yourself five years in the future?',
  'If you could travel anywhere in the world, where would you travel?',
  'What is the last movie you watched and would you recommend it?',
  'What is your favorite book and why?',
  "What is the weirdest dream you've had?",
  "What is something you've always wanted to buy?",
  'What is your favorite TV show and why?',
  'Share your idea of a perfect day.',
  'What is an unpopular opinion you have?',
  'Who is your favorite Disney character and why?',
  'What is something that you are putting off right now?',
  'What is your favorite song and why?',
  'Share something funny that happened to you this week.',
  "Is there something that you've dreamed of doing for a long time? Why haven't you done it?",
  'Share one of your favorite childhood memories.',
  'What advice would you give to your middle school self?',
  'What is a talent you wish you had?',
  'What is your favorite subject and why?',
  'If you were just given $20, how would you spend it?',
  'Who is someone you admire or look up to?',
  'Share a personal achievement you are proud of.',
  'Share a time you stepped outside of your comfort zone. Did it pay off?',
  'What are the top 3 things on your bucket list?',
  'What are your hobbies?',
  'What pet peeves do you have?',
  "What's your dream job?",
  'If you could switch lives with anyone in the world for a day, who would it be?',
  'Share an odd habit or quirk you have.',
  'How do you plan to spend tomorrow?',
  'How would you describe yourself in 3 words? Explain.',
  'What life lessons have you learned this past year?',
  'Share something you are grateful for.',
  'What is a memory you wish you could relive?',
  'If you could travel back in time to anywhere, where/when would it be?',
  'What is your spirit animal and why?',
  'Who is a fictional character you resonate with and why?',
  'What is the best gift you have ever received?',
  'Share a weird fear or phobia that you have.',
  'Where is your favorite place to go and why?',
  'What is something that you are looking forward to?',
  'What kind of music do you like to listen to?',
  'What is something you used to like that now you dislike?',
  'What is something you used to dislike but now you like?',
  "What is something new you've learned recently?",
  "What's your favorite holiday and why?",
  'If you had to become a teacher, what subject would you teach?',
  'If you could meet any celebrity, who would it be and why?',
  'If you were any kitchen utensil, which would you be and why?'
];

export default dbquestions;
